### ISSUE TITLE
Any way to recover wallet with seed??

### ISSUE THREAD

**Issue by koteknik** [bitshares/bitshares1-core#1560]
Hi,
I'm not sure if I'm in right place or this should be asked in forum but I guess the solution here will be beneficial for everyone.
I accidentaly lost the usb where I had my wallet backup and due to OS bugs I had to clen the filesystem, unfortunately .Bitshares folder is gone also and can't recover it with tools like scalpel or autopsy (they show the deleted folder but it's empty!). Is there a way to recover my wallet with the Seed passphrase??
I tried to recover it with web-wallet 0.x and 2.0; as I didn't made the upgrade already 2.0 doesn't accept Seed and 0.x return an empty wallet and when trying to recover accounts it states accounts don't belong to wallet!
What to do?

**Comment by nathanhourt** [comment]
I'd recommend filing this under https://github.com/bitshares/bitshares-2
