### ISSUE TITLE
I back up my wallet in 2014, come back in 2017 can't upgrade my wallet or login.

### ISSUE THREAD

**Issue by educatedwarrior** [bitshares/bitshares1-core#1563]
I backed up my wallet using 0.6.2 and have the password.  I tried importing the wallet into 7.0, 0.80, and 0.9.3c  ... non are accepting my password.   I know I have the correct password.

Seems like one problem after the next.  1st I get my BTS transfered to an account UNKNOWN, now I can't log in.   Frustrated.  Surprised I didn't commit suicide yet.

**Comment by testzcrypto** [comment]
- Download 0.6.2 (https://github.com/bitshares/bitshares1-core/releases/tag/bts%2F0.6.2)
- Restore your wallet from backup (don't wait when blockchain will be downloaded)
- Download and upgrade to 0.9.3c (https://github.com/bitshares/bitshares1-core/releases)
- Migrate to BitShares 2.0 using instruction from http://docs.bitshares.eu/migration

**Comment by educatedwarrior** [comment]
I tried downloading 0.6.2 and wasn't able to open my wallet ... so I believe my wallet was an even older version (Bitshares X).   Do you have any instructions to upgrade form Bitshares to 0.6.2?

**Comment by educatedwarrior** [comment]
Okay, I downloaded version 0.53.   I guess I have to work my way up to 0.62.   The only issue, my wallet won't connect to the blockchain.

**Comment by testzcrypto** [comment]
Yes, It's will **not** connect to blockchain. Upgrade to 0.9.3c and continue migration according instruction in my first reply.

**Comment by educatedwarrior** [comment]
Well I have another issue.   I'm currently getting key not found error / unknown delegate account in my wallet.  I don't know wheter to upgrade to 0.9.3c first or fix this error before going to 0.9.3c.  Any suggestions?

**Comment by testzcrypto** [comment]
Please start topic here: https://bitsharestalk.org/
At the forum more people can help you when here.

**Comment by educatedwarrior** [comment]
I've done that and nobody responded.  I can try again.  I'm getting application errors that is why I wanted to talk to you developers.

**Comment by educatedwarrior** [comment]
I've done that and nobody responded.  I can try again.  I'm getting application erros that is why I wanted to talk to you developers.

**Comment by educatedwarrior** [comment]
@testzcrypto , I appreciate the help you have given up to this point.  I was able to get my wallet up to 9.3c.  Just having issues connecting to a seed at this point.   Any suggestions would be appreciated.

**Comment by testzcrypto** [comment]
You don't need to connecting to seed, BitShares 1.0 network is down.
You need export you keys from the wallet using Settings->Console menu, import them to BitShares 2.0 wallet and claim your funds. Please check migration guide http://docs.bitshares.eu/migration

**Comment by abitmore** [comment]
Please ask/discuss in the forum. Check this post: https://bitsharestalk.org/index.php/topic,20822.0.html

**Comment by educatedwarrior** [comment]
Thanks @abitmore .    I followed the instruction int he post to my  chagrin.  I posted a screenshot of my balance.  None of this balance upgraded to Bitshares 2.0 when I imported the wallet.   Any suggestions?

![image](https://user-images.githubusercontent.com/4054610/26998470-053e616e-4d52-11e7-9772-a4e8d480b0a7.png)

**Comment by educatedwarrior** [comment]
I also did everything @testzcrypto  suggested above.

**Comment by educatedwarrior** [comment]
I posted here.  https://bitsharestalk.org/index.php/topic,9194.60.html

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php/topic,9194.msg307443.html#msg307443
