### ISSUE TITLE
Key Not Found Error / Unknown delegate account (32003)

### ISSUE THREAD

**Issue by educatedwarrior** [bitshares/bitshares1-core#1564]
I'm currently working on upgrading from version Bitshares  0.4.23.1 to 0.93C.

Going straight from 0.4.23.1 to 0.93C appears to not work.  So I'm incrementally upgrading to 0.6.2 first before I upgrade to 0.93C

When I upgraded to version 0.5.3 the wallet displays 8 errors.  Any suggestions on how to correct.  Some of my BTS which were awarded to me were never moved from the genesis block and the were all swept out by this UNKNOWN account on Oct 31, 2014

![image](https://user-images.githubusercontent.com/4054610/26876752-98287180-4b55-11e7-82a0-8197ff620838.png)

**Comment by educatedwarrior** [comment]
@vikramrajkumar ... do you have any suggestions.

**Comment by abitmore** [comment]
https://bitsharestalk.org/index.php/topic,20822.0.html

**Comment by educatedwarrior** [comment]
Didn't work brother @abitmore

**Comment by vikramrajkumar** [comment]
Continue discussion in forum: https://bitsharestalk.org/index.php/topic,9194.msg307443.html#msg307443
