### ISSUE TITLE
Register and transaction

### ISSUE THREAD

**Issue by KolosDan** [bitshares/bitshares1-core#1565]
Hello
Imagine, I have a custom BTS wallet provider. What I need to is registering new accounts and creating transactions for them.
1) Registering: Can I somehow pull it off without wallet API - just having my account keys and user information on preferable username 
2) Transactions: Can I create transactions again without using wallet API: having sending user's keys and all data needed for tx: to, amount, message and so on.

Thanks in advance, just really tired of exploring tons of docs and libraries. That is cool yeah, but the task is urgent

**Comment by abitmore** [comment]
This repository is stale, please follow latest info at https://github.com/bitshares/bitshares-core (the chain) and https://github.com/bitshares/bitshares-ui (the UI).

If only a wallet provider, what you need is to setup a web wallet and a faucet, no development work involved. Please ask in this channel: https://t.me/BTS_Node_Admins

Currently you can follow the steps here: http://docs.bitshares.eu/testnet/6-webwallet.html and http://docs.bitshares.eu/testnet/7-faucet.html, for mainnet, need to change some settings. (You do need to setup a node.)  (Sorry but the document I linked is a bit outdated, wish someone can share you a more up-to-date document.)

We do need better docs.
