### ISSUE TITLE
Problem with make!  I need help !

### ISSUE THREAD

**Issue by ying2025** [bitshares/bitshares1-core#1566]
ubuntu:~/bitshare/bitshares-core$make
[  0%] Performing autogen step for 'project_editline'
/home/zhr/bitshare/bitshares-core/libraries/fc/vendor/editline/autogen.sh: 3: /home/zhr/bitshare/bitshares-core/libraries/fc/vendor/editline/autogen.sh: autoreconf: not found
libraries/fc/CMakeFiles/project_editline.dir/build.make:117: recipe for target 'libraries/fc/vendor/editline/src/project_editline-stamp/project_editline-autogen' failed
make[2]: *** [libraries/fc/vendor/editline/src/project_editline-stamp/project_editline-autogen] Error 127
CMakeFiles/Makefile2:139: recipe for target 'libraries/fc/CMakeFiles/project_editline.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/project_editline.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by abitmore** [comment]
Please report to https://github.com/bitshares/bitshares-core
