### ISSUE TITLE
get_account_history_operations， different server node，different  data ？

### ISSUE THREAD

**Issue by wwwang89** [bitshares/bitshares1-core#1567]
Hi，when I connect the node in my app，"wss//bts.open.icowallet.net/ws", and call the method: get_account_history_operations and the parameter：

{"id":"14","method":"call","params":[4,"get_account_history_operations",["1.2.1097304",0,"1.11.0","1.11.0",60]]}，

and the error occurred（other most of the nodes met the same error！！！）：

{
	"id": 12,
	"jsonrpc": "2.0",
	"error": {
		"code": 1,
		"message": "Assert Exception: maybe_found != nullptr: Unable to find Object 2.9.0",
		"data": {
			"code": 10,
			"name": "assert_exception",
			"message": "Assert Exception",
			"stack": [{
				"context": {
					"level": "error",
					"file": "index.hpp",
					"line": 111,
					"method": "get",
					"hostname": "",
					"thread_name": "th_a",
					"timestamp": "2018-12-21T03:53:35"
				},
				"format": "maybe_found != nullptr: Unable to find Object ${id}",
				"data": {
					"id": "2.9.0"
				}
			}, {
				"context": {
					"level": "warn",
					"file": "websocket_api.cpp",
					"line": 125,
					"method": "on_message",
					"hostname": "",
					"thread_name": "th_a",
					"timestamp": "2018-12-21T03:53:35"
				},
				"format": "",
				"data": {
					"call.method": "call",
					"call.params": [4, "get_account_history_operations", ["1.2.1097304", 0, "1.11.0", "1.11.0", 60]]
				}
			}]
		}
	}
}

but when I connect  the node，"wss://ws.gdex.top", It can return the right data !
{
	"id": 12,
	"jsonrpc": "2.0",
	"result": [{
		"id": "1.11.641299970",
		"op": [0, {
			"fee": {
				"amount": 11211,
				"asset_id": "1.3.0"
			},
			"from": "1.2.1208495",
			"to": "1.2.1097304",
			"amount": {
				"amount": 1000000,
				"asset_id": "1.3.0"
			},
			"memo": {
				"from": "BTS7wCToEUmDm5mJux1cMyEuXuyocwth4kuRnJnK1YDVDEByiXHT4",
				"to": "BTS8LGsjtN3LzVSC3ci4A5Ji3xjVhdQy2jVnNbdMHg5UNLvqJCr7g",
				"nonce": "5549980068526969234",
				"message": "3526bd037ede96de2e0838a8ffdd197ff3b839e52b93948b8f82a86c54a2ba02a544bfdf87a22f974605146bc47155ef4778db7b44c143579af5985a03a957a3"
			},
			"extensions": []
		}],
		"result": [0, {}],
		"block_num": 33277997,
		"trx_in_block": 18,
		"op_in_trx": 0,
		"virtual_op": 64333
	}]
}

oh ,It confused me few days！ Any solutions or helps ？ Thanks very much！

**Comment by pmconrad** [comment]
You're probably talking about bitshares-2 nodes. This is the wrong repo, please use https://github.com/bitshares/bitshares-core/issues for future issues.

You may have found a bug that affects nodes with partial history. Please try
`{"id":"14","method":"call","params":[4,"get_account_history_operations",["1.2.1097304",0,"1.11.0","1.11.1",60]]}`
(Note that the `stop` parameter is now ...1 instead of ...0.)

**Comment by wwwang89** [comment]
> You're probably talking about bitshares-2 nodes. This is the wrong repo, please use https://github.com/bitshares/bitshares-core/issues for future issues.
> 
> You may have found a bug that affects nodes with partial history. Please try
> `{"id":"14","method":"call","params":[4,"get_account_history_operations",["1.2.1097304",0,"1.11.0","1.11.1",60]]}`
> (Note that the `stop` parameter is now ...1 instead of ...0.)


OK，it worked ！thanks for help ！

**Comment by pmconrad** [comment]
Thanks for the feedback. Please close this issue.
