### ISSUE TITLE
FC_ASSERT is bad style

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares1-core#956]
assert() in most languages means a conditional check that is optional to execute. It is more like an active comment, expressing a condition that the programmer expects to always be true. Therefore, skipping the evaluation of an assert should not lead to different behaviour of the software.

BitShares code uses FC_ASSERT in many places to check a condition and throw an exception if the condition is not true. Very often however, this check is not at all optional. For example, bts::blockchain::withdraw_operation() checks that the given amount is positive using FC_ASSERT. Skipping that check would allow to create transactions that withdraw a negative amount.

FC_ASSERT is basically a macro for "if(!TEST) throw exception" and there is no apparent means to switch this check off, so there is no bug. However, I find it unclear if FC_ASSERT is supposed to be an optional check and its use in BitShares code is wrong, or if it is supposed to be a non-optional check in which case the name FC_ASSERT is confusing and it should be renamed.

**Comment by tiger5226** [comment]
>For example, bts::blockchain::withdraw_operation() checks that the given amount is positive using FC_ASSERT. Skipping that check would allow to create transactions that withdraw a negative amount.

Did this cause the steemit blockchain to shutdown today?
